# System-wide configuration constants.
# Note that if default values are changed, database migrations will have to be rerun or a new migration created for
# the new values to take effect.

YEAR_RANGE = 1900..2100
# Default values
DEFAULT_EL_DOM_DEVELOPED = 1.3
DEFAULT_EL_DOM_DEVELOPING = 1.8
DEFAULT_EL_DOM_TRANSITIONAL = 1.8
DEFAULT_EL_SHORT_DEVELOPED = 1.5
DEFAULT_EL_SHORT_DEVELOPING = 2.0
DEFAULT_EL_SHORT_TRANSITIONAL = 2.0
DEFAULT_EL_MEDIUM_DEVELOPED = 1.6
DEFAULT_EL_MEDIUM_DEVELOPING = 2.0
DEFAULT_EL_MEDIUM_TRANSITIONAL = 2.0
DEFAULT_EL_LONG_DEVELOPED = 1.7
DEFAULT_EL_LONG_DEVELOPING = 2.2
DEFAULT_EL_LONG_TRANSITIONAL = 2.2
DEFAULT_EL_ULTRA_DEVELOPED = 2.4
DEFAULT_EL_ULTRA_DEVELOPING = 2.7
DEFAULT_EL_ULTRA_TRANSITIONAL = 2.7
# Not all default saturation values are applied. Some were required for a table update, but the intention is to
# override these on the input form anyway.
DEFAULT_SAT_DOM_DEVELOPED = 2030
DEFAULT_SAT_DOM_DEVELOPING= 2040
DEFAULT_SAT_DOM_TRANSITIONAL = 2040
DEFAULT_SAT_SHORT_DEVELOPED = 2030
DEFAULT_SAT_SHORT_DEVELOPING= 2040
DEFAULT_SAT_SHORT_TRANSITIONAL = 2040
DEFAULT_SAT_MEDIUM_DEVELOPED = 2030
DEFAULT_SAT_MEDIUM_DEVELOPING= 2040
DEFAULT_SAT_MEDIUM_TRANSITIONAL = 2040
DEFAULT_SAT_LONG_DEVELOPED = 2030
DEFAULT_SAT_LONG_DEVELOPING= 2040
DEFAULT_SAT_LONG_TRANSITIONAL = 2040
DEFAULT_SAT_ULTRA_DEVELOPED = 2030
DEFAULT_SAT_ULTRA_DEVELOPING= 2040
DEFAULT_SAT_ULTRA_TRANSITIONAL = 2040




